  ################################
  ### Configuration for lsp-ai ###
  ################################
  
  [language-server.lsp-ai]
  command = "lsp-ai"
  
  [language-server.lsp-ai.config.memory]
  file_store = { }
  
  # [language-server.lsp-ai.config.models.model1]
  # type = "anthropic"
  # chat_endpoint = "https://api.anthropic.com/v1/messages"
  # model = "claude-3-5-sonnet-20240620"
  # auth_token_env_var_name = ""
  #
  # [language-server.lsp-ai.config.models.model1]
  # type = "gemini"
  # chat_endpoint = "https://generativelanguage.googleapis.com/v1beta/models/"
  # model = "gemini-2.0-flash-latest"
  # auth_token_env_var_name = ""
  
  [[language-server.lsp-ai.config.chat]]
  trigger = "!C"
  action_display_name = "Chat"
  model = "model1"
  
  [language-server.lsp-ai.config.chat.parameters]
  max_context = 4096
  max_tokens = 1024
  system = "You are a code assistant chatbot. The user will ask you for assistance coding and you will do you best to answer succinctly and accurately"
  
  #################################
  ## Configuration for languages ##
  #################################
  
  
  #########################
  
  [language-server.steel-language-server]
  command = "steel-language-server"
  
  #[[language]]
  #name = "scheme"
  #language-servers = [ "steel-language-server" ]
  #formatter = { command = "dprint", args = ["fmt", "$file_path"] }
  #indent = { tab-width = 2, unit = "  " }
  
  
  ################C++######
  ################
  [[language]]
  name = "cpp"
  language-servers = [ "clangd" ]
  indent = { tab-width = 2, unit = "  " }
  formatter = { command = "dprint", args = ["fmt", "$file_path"] }
  
  [language-server.clangd]
  command = "clangd"
  args = ["--compile-commands-dir=build"]
  
  
  ######## rust #########
  
  [[language]]
  name = "rust"
  # Make sure your rust-analyzer path is correct, or just use the binary name if it's in your PATH
  language-servers = ["rust-analyzer"]
  formatter = { command = "rustfmt" }
  auto-format = true
  roots = [ "Cargo.toml", "Cargo.lock" ]
  indent = { tab-width = 2, unit = "  " }
  
  [language-server.rust-analyzer]
  command = "rust-analyzer"
  
  [language-server.iwe]
  command = "iwes"
  
  ## Every file type we intend to chat in needs to have lsp-ai enabled
  [[language]]
  name = "markdown"
  #language-servers = ["lsp-ai"]
  #language-servers = ["lsp-ai", "iwe"]
  language-servers = ["iwe"]
  formatter = { command = "dprint", args = ["fmt", "--stdin", "md"]}
  auto-format = true

[language-server.haskell-language-server]
command = "haskell-language-server-wrapper"
args = ["--lsp"]

[[language]]
name = "haskell"
scope = "source.haskell"
injection-regex = "haskell"
file-types = ["hs", "lhs"]
roots = ["stack.yaml", "cabal.project", "package.yaml", "*.cabal"]
language-servers = [ "haskell-language-server" ]
auto-format = true

[language-server.kotlin-language-server]
command = "kotlin-language-server" # PATH에 없다면 절대 경로 사용
args = []

[[language]]
name = "kotlin"
scope = "source.kt"
injection-regex = "kotlin"
file-types = ["kt", "kts"]
roots = ["settings.gradle", "settings.gradle.kts", "build.gradle", "build.gradle.kts"]
language-servers = [ "kotlin-language-server" ]
indent = { tab-width = 4, unit = "    " }
